import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createSceneModel} from './scene.js';

const $=id=>document.getElementById(id);
const model=createSceneModel();
const {items,rooms}=model;
let mode='property',selected=null,evening=false,gateOpen=false,topView=false,renderer,controls,camera,selectionBox;
let renderQueued=false;
const scene=new T.Scene();scene.background=new T.Color('#d6decd');scene.add(model.root);
const sun=new T.DirectionalLight('#fff5dc',3.5);sun.position.set(-18,35,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40,near:1,far:100});sun.shadow.normalBias=.03;sun.shadow.bias=-.0001;scene.add(sun);
const ambient=new T.HemisphereLight('#f1f4e8','#777f5c',2.3);scene.add(ambient);
const fill=new T.DirectionalLight('#d8e6f5',.8);fill.position.set(25,16,-25);scene.add(fill);
function draw(){renderQueued=false;if(renderer)renderer.render(scene,camera);}
function invalidate(){if(!renderQueued){renderQueued=true;requestAnimationFrame(draw);}}
function resize(){if(!renderer)return;const {width,height}=$('viewport').getBoundingClientRect();renderer.setSize(width,height,false);const previous=camera.aspect;camera.aspect=width/height;camera.updateProjectionMatrix();if(controls&&previous>0){const ratio=Math.max(1,1/camera.aspect*1.25)/Math.max(1,1/previous*1.25);camera.position.sub(controls.target).multiplyScalar(ratio).add(controls.target);controls.update();}invalidate();}
function frame(position=[0,1,0],size=45){if(!camera)return;const target=new T.Vector3(...position);const scale=Math.max(1,1/camera.aspect*1.25);const dir=topView?new T.Vector3(.001,1,.001):new T.Vector3(-.85,.9,-1.05).normalize();camera.position.copy(target).addScaledVector(dir,size*scale);camera.up.set(0,1,0);camera.lookAt(target);controls.target.copy(target);controls.update();invalidate();}
function resetView(){topView=false;$('plan-view').setAttribute('aria-pressed','false');frame(mode==='property'?[0,1,0]:[0,1,0],mode==='property'?47:25);}
try{
 renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.localClippingEnabled=true;
 renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label','Interactive fictional property. Drag to orbit; scroll or pinch to zoom. Arrow keys rotate, plus and minus zoom. All components can also be selected from the tools.');$('viewport').append(renderer.domElement);
 camera=new T.PerspectiveCamera(42,1,.1,350);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=4;controls.maxDistance=110;controls.maxPolarAngle=Math.PI*.48;controls.addEventListener('change',invalidate);
 new ResizeObserver(resize).observe($('viewport'));resize();resetView();
 renderer.domElement.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(event.key)){event.preventDefault();const offset=camera.position.clone().sub(controls.target);const spherical=new T.Spherical().setFromVector3(offset);if(event.key==='ArrowLeft')spherical.theta-=.12;if(event.key==='ArrowRight')spherical.theta+=.12;if(event.key==='ArrowUp')spherical.phi=Math.max(.05,spherical.phi-.1);if(event.key==='ArrowDown')spherical.phi=Math.min(1.45,spherical.phi+.1);if(['+','='].includes(event.key))spherical.radius=Math.max(4,spherical.radius*.88);if(event.key==='-')spherical.radius=Math.min(110,spherical.radius*1.12);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(spherical));controls.update();invalidate();}});
 const ray=new T.Raycaster();let down;
 renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);
 renderer.domElement.addEventListener('pointerup',e=>{if(mode==='property'||!down||Math.hypot(down[0]-e.clientX,down[1]-e.clientY)>5)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);for(const hit of ray.intersectObjects(items.map(i=>i.object),true)){let o=hit.object,visible=true;while(o){if(!o.visible)visible=false;o=o.parent;}if(!visible)continue;const item=items.find(i=>{let obj=hit.object;while(obj){if(obj===i.object)return true;obj=obj.parent;}return false;});if(item){select(item.id,false);break;}}});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('fallback').hidden=false;});
 renderer.domElement.addEventListener('webglcontextrestored',()=>{$('fallback').hidden=true;invalidate();});
}catch{ $('fallback').hidden=false; }

const copy={property:['01 / The whole picture','A place, understood.','Drag to orbit · scroll to zoom'],inside:['02 / Beneath the surface','See the build.','Select a component · drag to orbit'],find:['03 / Behind the walls','Know where it goes.','Search a system · inspect its route']};
function setMode(next){mode=next;selected=null;clearSelection();model.setMode(mode);if(mode==='inside')model.layers.services.visible=false;document.body.dataset.mode=mode;for(const b of document.querySelectorAll('.collections [data-mode]'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));for(const name of ['property','inside','find'])$(name+'-panel').hidden=name!==mode;const [kicker,title,hint]=copy[mode];$('scene-kicker').textContent=kicker;$('scene-title').textContent=title;$('scene-hint').textContent=hint;$('structure-layer').checked=true;$('services-layer').checked=false;$('section').value='100';$('section-value').textContent='Full frame';model.setSection(1);renderResults();resetView();const url=new URL(location.href);if(mode==='property')url.searchParams.delete('collection');else url.searchParams.set('collection',mode);history.replaceState({},'',url);}
for(const button of document.querySelectorAll('.collections [data-mode]'))button.onclick=()=>setMode(button.dataset.mode);
for(const button of document.querySelectorAll('[data-go]'))button.onclick=()=>setMode(button.dataset.go);
$('gate').onclick=()=>{gateOpen=!gateOpen;model.setGate(gateOpen);$('gate').setAttribute('aria-pressed',String(gateOpen));$('gate').firstChild.textContent=gateOpen?'Close the gate ':'Open the gate ';invalidate();};
$('light-mode').onclick=()=>{evening=!evening;model.setNight(evening);document.body.dataset.evening=String(evening);$('light-mode').setAttribute('aria-pressed',String(evening));$('light-mode').textContent=evening?'Daylight':'Evening';scene.background.set(evening?'#233239':'#d6decd');sun.intensity=evening?.28:3.5;ambient.intensity=evening?.65:2.3;fill.intensity=evening?.3:.8;invalidate();};
$('home-view').onclick=resetView;
$('plan-view').onclick=()=>{topView=!topView;$('plan-view').setAttribute('aria-pressed',String(topView));frame(selected?.position||[0,0,0],mode==='property'?49:29);};
$('section').oninput=()=>{const v=Number($('section').value)/100;model.setSection(v);$('section-value').textContent=v===1?'Full frame':Math.round(v*100)+'%';invalidate();};
$('structure-layer').onchange=()=>{model.layers.structure.visible=$('structure-layer').checked;invalidate();};
$('services-layer').onchange=()=>{model.layers.services.visible=$('services-layer').checked;invalidate();};

const palette={plumbing:'#d7773d',electrical:'#edaf53',structure:'#d9b682',hvac:'#88b99b',septic:'#ba91c2'};
function resultButton(item){const b=document.createElement('button');b.className='result';b.dataset.item=item.id;b.setAttribute('aria-pressed',String(selected?.id===item.id));const dot=document.createElement('span');dot.className='dot';dot.style.setProperty('--dot',palette[item.category]||'#adb7c0');dot.setAttribute('aria-hidden','true');const text=document.createElement('span');const title=document.createElement('strong');title.textContent=item.title;const sub=document.createElement('small');sub.textContent=item.room;text.append(title,sub);b.append(dot,text);b.onclick=()=>select(item.id);return b;}
function renderResults(){const query=$('search').value.toLowerCase().trim();const tokens=query.split(/\W+/).filter(t=>t&&!['where','is','are','the','this','that','my','a','an','find'].includes(t));const terms={plumbing:'line pipe drain waste toilet',electrical:'plug socket outlet wire wiring cable circuit power',structure:'frame framing stud studs truss trusses',hvac:'air ac duct vent heat supply',septic:'tank tanks drainage waste sewer'};const matches=items.filter(i=>tokens.every(token=>[i.title,i.category,i.room,i.description,i.id,terms[i.category]].join(' ').toLowerCase().includes(token)));$('results').replaceChildren(...matches.map(resultButton));$('result-status').textContent=matches.length?`${matches.length} ${matches.length===1?'component':'components'}${query?' matching “'+$('search').value+'”':''}`:'No matches. Try toilet, outlet, truss, duct, or septic.';$('structure-items').replaceChildren(...items.filter(i=>i.category==='structure').map(resultButton));}
$('search').oninput=renderResults;
for(const b of document.querySelectorAll('[data-search]'))b.onclick=()=>{$('search').value=b.dataset.search;renderResults();$('search').focus();};
function clearSelection(){selected=null;$('selection').hidden=true;if(selectionBox){scene.remove(selectionBox);selectionBox.geometry.dispose();selectionBox.material.dispose();selectionBox=null;}for(const item of items)if(item.object)item.object.visible=true;renderResults();invalidate();}
function select(id,move=true){const item=items.find(i=>i.id===id);if(!item)return;clearSelection();selected=item;if(item.category==='structure'){model.layers.structure.visible=true;model.layers.services.visible=false;}else{model.layers.services.visible=true;model.layers.structure.visible=true;}model.layers.fixtures.visible=true;for(const other of items){if(other.object&&other.category!==item.category)other.object.visible=false;}item.object.visible=true;item.object.updateWorldMatrix(true,true);selectionBox=new T.BoxHelper(item.object,'#f97316');selectionBox.material.depthTest=false;selectionBox.renderOrder=999;scene.add(selectionBox);$('selection').hidden=false;$('selected-category').textContent=`${item.category} / illustrative component`;$('selected-title').textContent=item.title;$('selected-description').textContent=item.description;$('selected-room').textContent=item.room;$('selected-dimensions').textContent=item.dimensionText||item.dimensions?.map(v=>`${v} ft`).join(' × ')||'Demonstration specification';renderResults();if(move){topView=false;$('plan-view').setAttribute('aria-pressed','false');const bounds=new T.Box3().setFromObject(item.object);const size=bounds.getSize(new T.Vector3()).length();frame(item.position,Math.max(12,Math.min(32,size*1.6)));}invalidate();}
$('clear-selection').onclick=()=>{clearSelection();model.setMode(mode);if(mode==='inside')model.layers.services.visible=$('services-layer').checked;resetView();};

function svgEl(name,attrs={}){const element=document.createElementNS('http://www.w3.org/2000/svg',name);for(const [key,value]of Object.entries(attrs))element.setAttribute(key,String(value));return element;}
function drawPlan(){const svg=svgEl('svg',{viewBox:'-10 -6 27 16',role:'img','aria-label':'Fictional floor plan and selected component location'});const floor=svgEl('rect',{x:-9,y:-4.5,width:18,height:9,fill:'#e4e6dc',stroke:'#354c41','stroke-width':.1});svg.append(floor);for(const room of rooms){const x=room.x??0,z=room.z??0,w=room.width??3,d=room.depth??3;const rect=svgEl('rect',{x,y:z,width:w,height:d,fill:'#f8f8f0',stroke:'#728377','stroke-width':.055});svg.append(rect);const text=svgEl('text',{x:x+w/2,y:selected?.room===room.title?z+d-.25:z+d/2,'font-size':.68,fill:'#304a3c','text-anchor':'middle','font-family':'Barlow, sans-serif'});text.textContent=room.title||room.name||'Room';svg.append(text);}
 for(const item of items.filter(i=>i.category!=='structure')){const [x,,z]=item.position;const active=selected?.id===item.id;const color=palette[item.category]||'#788e82';const dot=svgEl('circle',{cx:x,cy:z,r:active?.26:.14,fill:color,stroke:active?'#101f18':'none','stroke-width':.1});svg.append(dot);if(active){const side=x>7?-1:1;const line=svgEl('path',{d:`M ${x} ${z} L ${x+side*1.6} ${z-1.8} L ${x+side*5} ${z-1.8}`,stroke:'#1a3827','stroke-width':.07,fill:'none'});const text=svgEl('text',{x:x+side*1.6,y:z-2.05,'text-anchor':side===1?'start':'end','font-size':.68,fill:'#182e23','font-family':'Barlow, sans-serif'});text.textContent=item.title;svg.append(line,text);}}
 if(selected?.category==='structure'){const [x,,z]=selected.position;svg.append(svgEl('circle',{cx:x,cy:z,r:.35,stroke:'#dc7d25','stroke-width':.13,fill:'none'}));}
 const scale=svgEl('path',{d:'M -9 7.5 v .3 M -9 7.65 h 3.048 M -5.952 7.5 v .3',stroke:'#203d2c','stroke-width':.08,fill:'none'});const scaleText=svgEl('text',{x:-7.476,y:8.5,'font-size':.68,fill:'#203d2c','text-anchor':'middle','font-family':'Barlow, sans-serif'});scaleText.textContent='10′ 0″';svg.append(scale,scaleText);$('plan-drawing').replaceChildren(svg);$('plan-description').textContent=selected?`${selected.title} · ${selected.room}. The marker locates this example component in the fictional model.`:'A fictional floor plan. Colored points locate example systems; the 3D view reveals their routes.';}
function openDialog(dialog){window.frameElement?.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'});dialog.showModal();}
function openPlan(){drawPlan();openDialog($('plan-dialog'));}
$('show-plan').onclick=openPlan;$('source-plan').onclick=openPlan;$('about').onclick=()=>openDialog($('about-dialog'));
for(const button of document.querySelectorAll('.dialog-close'))button.onclick=()=>button.closest('dialog').close();
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('exit').href=location.pathname.includes('/examples/lab/concepts/')?'/examples/lab/':'./overview.html';
const requested=new URLSearchParams(location.search).get('collection');setMode(['inside','find'].includes(requested)?requested:'property');
document.addEventListener('lab:replay',event=>{event.preventDefault();gateOpen=false;model.setGate(false);$('gate').setAttribute('aria-pressed','false');$('gate').firstChild.textContent='Open the gate ';$('search').value='';setMode('property');});
window.addEventListener('pagehide',()=>{controls?.dispose();renderer?.dispose();});
// A small, read-only state surface for deterministic integration checks.
window.propertyExplorer=Object.freeze({getState:()=>({mode,selected:selected?.id||null,gateOpen,evening,webgl:!!renderer,components:items.length,triangles:renderer?.info.render.triangles||0}),getComponents:()=>items.map(({id,title,category,room,dimensionText})=>({id,title,category,room,dimensionText}))});
